### ISSUE TITLE
gl_python_driver_udp error 01

### ISSUE THREAD

**Issue by NamWoo** [NamWoo/preparation#1]
# python3 gl_python_driver_udp.py

```
nw@n86:~/catkin_ws/src/gl_python_driver_udp$ python3 gl_python_driver_udp.py
main start
::: Udp communication start!!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/nw/catkin_ws/src/gl_python_driver_udp/udp_comm.py", line 73, in run
    self.protocol.connection_lost(error)
  File "gl_python_driver_udp.py", line 53, in connection_lost
    raise exc
  File "/home/nw/catkin_ws/src/gl_python_driver_udp/udp_comm.py", line 59, in run
    data = self.sock.recvfrom(1100)[0]
socket.timeout: timed out

Serial Num : [ERROR] Serial Number is not received
Traceback (most recent call last):
  File "gl_python_driver_udp.py", line 359, in <module>
    udp_gl.SetFrameDataEnable(True)
  File "gl_python_driver_udp.py", line 307, in SetFrameDataEnable
    self.write_packet(PI, PL, SM, CAT0, CAT1, DTn)
  File "gl_python_driver_udp.py", line 122, in write_packet
    self.transport.write(bytes(bytearray(self.buff_list)))
AttributeError: 'NoneType' object has no attribute 'write'

```

**Comment by NamWoo** [comment]
# ping test

```
nw@n86:~/catkin_ws/src/gl_python_driver_udp$ ping 10.110.1.3
PING 10.110.1.3 (10.110.1.3) 56(84) bytes of data.
64 bytes from 10.110.1.3: icmp_seq=1 ttl=64 time=0.096 ms
64 bytes from 10.110.1.3: icmp_seq=2 ttl=64 time=0.059 ms
64 bytes from 10.110.1.3: icmp_seq=3 ttl=64 time=0.066 ms
64 bytes from 10.110.1.3: icmp_seq=4 ttl=64 time=0.074 ms
^C
--- 10.110.1.3 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3078ms
rtt min/avg/max/mdev = 0.059/0.073/0.096/0.017 ms
```

# ifconfig

```
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.110.1.3  netmask 255.255.255.0  broadcast 10.110.1.255
```

**Comment by NamWoo** [comment]
# roslaunch gl_ros_driver_udp 

```
nw@n86:~/catkin_ws/src/gl_python_driver_udp$ roslaunch gl_ros_driver_udp gl_ros_driver_udp.launch 
... logging to /home/nw/.ros/log/476ca856-1f5e-11ec-8f2b-48b02d076b01/roslaunch-n86-14401.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://n86:37877/

SUMMARY
========

PARAMETERS
 * /gl_ros_driver_udp_node/frame_id: laser
 * /gl_ros_driver_udp_node/gl_ip: 10.110.1.2
 * /gl_ros_driver_udp_node/gl_port: 2000
 * /gl_ros_driver_udp_node/pc_port: 3000
 * /gl_ros_driver_udp_node/pub_topicname_lidar: scan
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /
    gl_ros_driver_udp_node (gl_ros_driver_udp/gl_ros_driver_udp_node)

auto-starting new master
process[master]: started with pid [14411]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 476ca856-1f5e-11ec-8f2b-48b02d076b01
process[rosout-1]: started with pid [14424]
started core service [/rosout]
process[gl_ros_driver_udp_node-2]: started with pid [14427]
Socket START [11]
Serial Num : G310H1600017

```
